# Generated by Django 3.2.9 on 2021-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.TextField(null=True),
        ),
    ]
