# Generated by Django 3.2.9 on 2021-11-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0002_alter_task_task_notify_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
