# Generated by Django 3.2.9 on 2021-11-26 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskr', '0003_remove_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_data',
        ),
        migrations.AddField(
            model_name='notification',
            name='assignedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='AssignedTo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='heading',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_To', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 9, 13, 52, 441252)),
        ),
    ]
