# Generated by Django 3.2.9 on 2021-11-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0006_auto_20211126_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='assignedTo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 9, 18, 35, 206038)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 9, 18, 35, 205633)),
        ),
    ]
