# Generated by Django 3.2.9 on 2021-11-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0011_auto_20211129_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 16, 11, 38, 233651)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 16, 11, 38, 232787)),
        ),
    ]
