# Generated by Django 3.2.9 on 2021-11-29 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0012_auto_20211129_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedTo', models.TextField()),
                ('taskId', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 31, 3, 820515)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 31, 3, 819913)),
        ),
    ]
