# Generated by Django 3.2.9 on 2021-11-30 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0014_auto_20211129_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytasks',
            name='notify_time',
        ),
        migrations.AddField(
            model_name='celerytasks',
            name='heading',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 4, 46, 45, 487340)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 4, 46, 45, 486774)),
        ),
    ]
