# Generated by Django 3.2.9 on 2021-11-30 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0017_auto_20211130_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytasks',
            name='heading',
        ),
        migrations.AddField(
            model_name='celerytasks',
            name='task_heading',
            field=models.TextField(default=datetime.datetime(2021, 12, 7, 4, 50, 12, 592247)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 4, 50, 12, 591219)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 4, 50, 12, 585952)),
        ),
    ]
