# Generated by Django 3.2.9 on 2021-11-30 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0018_auto_20211130_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytasks',
            name='task_heading',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 4, 51, 4, 409575)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 4, 51, 4, 409151)),
        ),
    ]
