# Generated by Django 3.2.9 on 2021-11-30 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0020_auto_20211130_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 12, 30, 56, 298020)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notify_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 12, 30, 56, 297424)),
        ),
    ]
